In [1]:
import numpy as np

## Datatype & Attributes

In [4]:
#main type --> ndarray | n dimension's array 

In [6]:
a1 = np.array([1,2,3])

In [8]:
a1

array([1, 2, 3])

In [10]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[5,8,4],[4,7,8]])
a2

array([[5, 8, 4],
       [4, 7, 8]])

In [43]:
a3 = np.array([[[[1,2,3.5],[4.5,1,3],[7,5.6,9]],[[1,2,5.4],[7,4.8,9],[4,1.3,9]],[[4,1,2.3],[7,1,4.5],[7,1.8,9]]],[[[1,2,3.5],[4.5,1,3],[7,5.6,9]],[[1,2,5.4],[7,4.8,9],[4,1.3,9]],[[4,1,2.3],[7,1,4.5],[7,1.8,9]]]])

In [45]:
a3

array([[[[1. , 2. , 3.5],
         [4.5, 1. , 3. ],
         [7. , 5.6, 9. ]],

        [[1. , 2. , 5.4],
         [7. , 4.8, 9. ],
         [4. , 1.3, 9. ]],

        [[4. , 1. , 2.3],
         [7. , 1. , 4.5],
         [7. , 1.8, 9. ]]],


       [[[1. , 2. , 3.5],
         [4.5, 1. , 3. ],
         [7. , 5.6, 9. ]],

        [[1. , 2. , 5.4],
         [7. , 4.8, 9. ],
         [4. , 1.3, 9. ]],

        [[4. , 1. , 2.3],
         [7. , 1. , 4.5],
         [7. , 1.8, 9. ]]]])

In [47]:
a1.shape

(3,)

In [49]:
a2.shape

(2, 3)

In [51]:
a3.shape

(2, 3, 3, 3)

In [61]:
#understand the way write the shape. it is like coming out from the inside. if like [1,2,3] --> (3, )
#if [2,3,9],[5,5,8] it's shape --> (2,3)

In [63]:
a1.dtype

dtype('int32')

In [65]:
a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'))

In [67]:
a1.size, a2.size, a3.size

(3, 6, 54)

In [69]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [71]:
#lets create a data frame
import pandas as pd

In [75]:
df = pd.DataFrame(a2)

In [77]:
df

0  1  2
0  5  8  4
1  4  7  8

In [79]:
# we can not convert here, it is gives an error || only 2d arrays can converted into data frame

## Creating arrays

In [82]:
sample_array = np.array([2,1,6])
sample_array

array([2, 1, 6])

In [84]:
sample_array.dtype

dtype('int32')

In [88]:
ones = np.ones((3,3,3,3), dtype=int) 

In [90]:
ones

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]])

In [92]:
type(ones)

numpy.ndarray

In [94]:
zeros = np.zeros((2,2), dtype= int)

In [96]:
zeros

array([[0, 0],
       [0, 0]])

In [100]:
zeros.dtype

dtype('int32')

In [106]:
range_array = np.arange(5)
range_array

array([0, 1, 2, 3, 4])

In [108]:
range_array1 = np.arange(5,9)
range_array1

array([5, 6, 7, 8])

In [110]:
range_array2 = np.arange(1,10,3)
range_array2

array([1, 4, 7])

In [126]:
#random arrray | low - high - size - type

In [128]:
random_array = np.random.randint(8)
random_array

5

In [130]:
ra2 = np.random.randint(5,10)
ra2

9

In [132]:
ra4 = np.random.randint(1,5,8,dtype=int)
ra4

array([4, 2, 1, 1, 1, 4, 3, 1])

In [134]:
ra5 = np.random.randint(0,15,size=(3,3,5))
ra5

array([[[ 3, 12,  2, 14,  7],
        [ 5, 11,  9, 11,  7],
        [ 3,  8,  6,  9, 13]],

       [[ 3, 12,  8,  9,  4],
        [ 9, 13,  8, 14, 13],
        [10,  9, 12,  1, 14]],

       [[14,  5,  5,  7,  2],
        [ 3,  5,  3, 11,  1],
        [12,  6, 11, 11, 11]]])

In [136]:
## here we can give the size as the shape 

In [142]:
#here we gives only the shape
#in python random() generate random floats between 0 - 1
ra6 = np.random.random((3,2))
ra6

array([[0.34028382, 0.69713608],
       [0.02298905, 0.45758436],
       [0.13450032, 0.14908774]])

In [148]:
#this can be achive using np.random.rand() also
ar7 = np.random.rand(3,2)
ar7

array([[0.35484734, 0.38187125],
       [0.36042919, 0.70602272],
       [0.37093123, 0.50068691]])

In [150]:
## similer result we get


Random seeds -- pseudo-random number


up here random function that we use genarate different random number whenever it run
again and again

In [218]:
#but
np.random.seed(seed=0)
ra8 = np.random.randint(10,size=(3,5))
ra8

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [220]:
#the elements of array's mpt change time to time when it run

In [222]:
np.random.seed(seed=0)
ra9 = np.random.random((5,3))
ra9

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## viewing arrays and matrices

uniqe array  

In [226]:
np.unique([1,2,5,4,2,1,3,2,1,2])

array([1, 2, 3, 4, 5])

In [228]:
a = np.array([[1,2,3,1,2],[1,5,4,2,1]])

In [230]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [232]:
np.unique(a, axis=0)

array([[1, 2, 3, 1, 2],
       [1, 5, 4, 2, 1]])

<--- this remove the same rows not the elements  

In [239]:
a2 = np.array([[1,2,1],[1,2,1],[3,5,3]])

In [243]:
np.unique(a2, axis=0)

array([[1, 2, 1],
       [3, 5, 3]])

there was 1,2,1 2 rwos before using uniqu function and now have only one

In [246]:
##indexing

In [250]:
ar = np.random.randint(10, size=(3,3,3))
ar

array([[[1, 7, 9],
        [9, 3, 6],
        [7, 2, 0]],

       [[3, 5, 9],
        [4, 4, 6],
        [4, 4, 3]],

       [[4, 4, 8],
        [4, 3, 7],
        [5, 5, 0]]])

In [252]:
ar[0]

array([[1, 7, 9],
       [9, 3, 6],
       [7, 2, 0]])

In [254]:
ar[2]

array([[4, 4, 8],
       [4, 3, 7],
       [5, 5, 0]])

In [256]:
ar[0,0]

array([1, 7, 9])

In [258]:
ar[0,1]

array([9, 3, 6])

In [260]:
ar[0,0,0]

1

matrix = array with dimension higher than 1

In [264]:
ar

array([[[1, 7, 9],
        [9, 3, 6],
        [7, 2, 0]],

       [[3, 5, 9],
        [4, 4, 6],
        [4, 4, 3]],

       [[4, 4, 8],
        [4, 3, 7],
        [5, 5, 0]]])

In [266]:
ar[:2]

array([[[1, 7, 9],
        [9, 3, 6],
        [7, 2, 0]],

       [[3, 5, 9],
        [4, 4, 6],
        [4, 4, 3]]])

In [268]:
ar[:2, :2]

array([[[1, 7, 9],
        [9, 3, 6]],

       [[3, 5, 9],
        [4, 4, 6]]])

In [270]:
ar[:2, :2, :2]

array([[[1, 7],
        [9, 3]],

       [[3, 5],
        [4, 4]]])

In [272]:
ar.ndim

3

In [274]:
ar[:, :, :2]

array([[[1, 7],
        [9, 3],
        [7, 2]],

       [[3, 5],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 3],
        [5, 5]]])

gives only the 1st 2 element in inermost arrays, lower lvel array

In [277]:
#ex :
arr = np.random.randint(10, size=(4,4,4,5))
arr

array([[[[1, 5, 9, 3, 0],
         [5, 0, 1, 2, 4],
         [2, 0, 3, 2, 0],
         [7, 5, 9, 0, 2]],

        [[7, 2, 9, 2, 3],
         [3, 2, 3, 4, 1],
         [2, 9, 1, 4, 6],
         [8, 2, 3, 0, 0]],

        [[6, 0, 6, 3, 3],
         [8, 8, 8, 2, 3],
         [2, 0, 8, 8, 3],
         [8, 2, 8, 4, 3]],

        [[0, 4, 3, 6, 9],
         [8, 0, 8, 5, 9],
         [0, 9, 6, 5, 3],
         [1, 8, 0, 4, 9]]],


       [[[6, 5, 7, 8, 8],
         [9, 2, 8, 6, 6],
         [9, 1, 6, 8, 8],
         [3, 2, 3, 6, 3]],

        [[6, 5, 7, 0, 8],
         [4, 6, 5, 8, 2],
         [3, 9, 7, 5, 3],
         [4, 5, 3, 3, 7]],

        [[9, 9, 9, 7, 3],
         [2, 3, 9, 7, 7],
         [5, 1, 2, 2, 8],
         [1, 5, 8, 4, 0]],

        [[2, 5, 5, 0, 8],
         [1, 1, 0, 3, 8],
         [8, 4, 4, 0, 9],
         [3, 7, 3, 2, 1]]],


       [[[1, 2, 1, 4, 2],
         [5, 5, 5, 2, 5],
         [7, 7, 6, 1, 6],
         [7, 2, 3, 1, 9]],

        [[5, 9, 9, 2, 0],
         [9, 1, 

In [279]:
#now i am gonna get array with : 4,4,4,4 shape
arr[:,:,:,:4]

array([[[[1, 5, 9, 3],
         [5, 0, 1, 2],
         [2, 0, 3, 2],
         [7, 5, 9, 0]],

        [[7, 2, 9, 2],
         [3, 2, 3, 4],
         [2, 9, 1, 4],
         [8, 2, 3, 0]],

        [[6, 0, 6, 3],
         [8, 8, 8, 2],
         [2, 0, 8, 8],
         [8, 2, 8, 4]],

        [[0, 4, 3, 6],
         [8, 0, 8, 5],
         [0, 9, 6, 5],
         [1, 8, 0, 4]]],


       [[[6, 5, 7, 8],
         [9, 2, 8, 6],
         [9, 1, 6, 8],
         [3, 2, 3, 6]],

        [[6, 5, 7, 0],
         [4, 6, 5, 8],
         [3, 9, 7, 5],
         [4, 5, 3, 3]],

        [[9, 9, 9, 7],
         [2, 3, 9, 7],
         [5, 1, 2, 2],
         [1, 5, 8, 4]],

        [[2, 5, 5, 0],
         [1, 1, 0, 3],
         [8, 4, 4, 0],
         [3, 7, 3, 2]]],


       [[[1, 2, 1, 4],
         [5, 5, 5, 2],
         [7, 7, 6, 1],
         [7, 2, 3, 1]],

        [[5, 9, 9, 2],
         [9, 1, 9, 0],
         [0, 4, 8, 4],
         [3, 8, 8, 7]],

        [[3, 8, 7, 7],
         [8, 4, 7, 0],
         [

In [281]:
#lets get arr with the shape, 4,2,2,2
arr[:,:2, :2, :2]

array([[[[1, 5],
         [5, 0]],

        [[7, 2],
         [3, 2]]],


       [[[6, 5],
         [9, 2]],

        [[6, 5],
         [4, 6]]],


       [[[1, 2],
         [5, 5]],

        [[5, 9],
         [9, 1]]],


       [[[1, 6],
         [3, 1]],

        [[8, 3],
         [4, 9]]]])