In [1]:
import numpy as np

## Datatype & Attributes

In [4]:
#main type --> ndarray | n dimension's array 

In [6]:
a1 = np.array([1,2,3])

In [8]:
a1

array([1, 2, 3])

In [10]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[5,8,4],[4,7,8]])
a2

array([[5, 8, 4],
       [4, 7, 8]])

In [43]:
a3 = np.array([[[[1,2,3.5],[4.5,1,3],[7,5.6,9]],[[1,2,5.4],[7,4.8,9],[4,1.3,9]],[[4,1,2.3],[7,1,4.5],[7,1.8,9]]],[[[1,2,3.5],[4.5,1,3],[7,5.6,9]],[[1,2,5.4],[7,4.8,9],[4,1.3,9]],[[4,1,2.3],[7,1,4.5],[7,1.8,9]]]])

In [45]:
a3

array([[[[1. , 2. , 3.5],
         [4.5, 1. , 3. ],
         [7. , 5.6, 9. ]],

        [[1. , 2. , 5.4],
         [7. , 4.8, 9. ],
         [4. , 1.3, 9. ]],

        [[4. , 1. , 2.3],
         [7. , 1. , 4.5],
         [7. , 1.8, 9. ]]],


       [[[1. , 2. , 3.5],
         [4.5, 1. , 3. ],
         [7. , 5.6, 9. ]],

        [[1. , 2. , 5.4],
         [7. , 4.8, 9. ],
         [4. , 1.3, 9. ]],

        [[4. , 1. , 2.3],
         [7. , 1. , 4.5],
         [7. , 1.8, 9. ]]]])

In [47]:
a1.shape

(3,)

In [49]:
a2.shape

(2, 3)

In [51]:
a3.shape

(2, 3, 3, 3)

In [61]:
#understand the way write the shape. it is like coming out from the inside. if like [1,2,3] --> (3, )
#if [2,3,9],[5,5,8] it's shape --> (2,3)

In [63]:
a1.dtype

dtype('int32')

In [65]:
a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'))

In [67]:
a1.size, a2.size, a3.size

(3, 6, 54)

In [69]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [71]:
#lets create a data frame
import pandas as pd

In [75]:
df = pd.DataFrame(a2)

In [77]:
df

0  1  2
0  5  8  4
1  4  7  8

In [79]:
# we can not convert here, it is gives an error || only 2d arrays can converted into data frame

## Creating arrays

In [82]:
sample_array = np.array([2,1,6])
sample_array

array([2, 1, 6])

In [84]:
sample_array.dtype

dtype('int32')

In [88]:
ones = np.ones((3,3,3,3), dtype=int) 

In [90]:
ones

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]])

In [92]:
type(ones)

numpy.ndarray

In [94]:
zeros = np.zeros((2,2), dtype= int)

In [96]:
zeros

array([[0, 0],
       [0, 0]])

In [100]:
zeros.dtype

dtype('int32')

In [106]:
range_array = np.arange(5)
range_array

array([0, 1, 2, 3, 4])

In [108]:
range_array1 = np.arange(5,9)
range_array1

array([5, 6, 7, 8])

In [110]:
range_array2 = np.arange(1,10,3)
range_array2

array([1, 4, 7])

In [126]:
#random arrray | low - high - size - type

In [128]:
random_array = np.random.randint(8)
random_array

5

In [130]:
ra2 = np.random.randint(5,10)
ra2

9

In [132]:
ra4 = np.random.randint(1,5,8,dtype=int)
ra4

array([4, 2, 1, 1, 1, 4, 3, 1])

In [134]:
ra5 = np.random.randint(0,15,size=(3,3,5))
ra5

array([[[ 3, 12,  2, 14,  7],
        [ 5, 11,  9, 11,  7],
        [ 3,  8,  6,  9, 13]],

       [[ 3, 12,  8,  9,  4],
        [ 9, 13,  8, 14, 13],
        [10,  9, 12,  1, 14]],

       [[14,  5,  5,  7,  2],
        [ 3,  5,  3, 11,  1],
        [12,  6, 11, 11, 11]]])

In [136]:
## here we can give the size as the shape 

In [142]:
#here we gives only the shape
#in python random() generate random floats between 0 - 1
ra6 = np.random.random((3,2))
ra6

array([[0.34028382, 0.69713608],
       [0.02298905, 0.45758436],
       [0.13450032, 0.14908774]])

In [148]:
#this can be achive using np.random.rand() also
ar7 = np.random.rand(3,2)
ar7

array([[0.35484734, 0.38187125],
       [0.36042919, 0.70602272],
       [0.37093123, 0.50068691]])

In [150]:
## similer result we get