https://scikit-learn.org/stable/datasets/real_world.html    ->> can find datasets for practice

In [1]:
import numpy as np
import pandas as pd


In [2]:
import matplotlib.pyplot as plt


In [3]:
from sklearn.datasets import fetch_california_housing

In [4]:
housing = fetch_california_housing()

In [5]:
housing_df = pd.DataFrame(housing.data, columns=housing.feature_names)
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [6]:
housing_df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [7]:
housing_df["Target"] = housing.target


In [8]:
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [9]:
housing_df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Target        0
dtype: int64

No any missing values

In [10]:
housing_df.dtypes

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
Target        float64
dtype: object

all tha features are numerical 

In [11]:
x = housing_df.drop("Target", axis =1)
y = housing_df["Target"]

In [12]:
np.random.seed(seed = 42)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [13]:
model.score(x_test, y_test)

0.8065734772187598

### Regression model evaluation matrix:

model evaluation matricms documentation : https://scikit-learn.org/stable/modules/model_evaluation.html

    1. R^2 (pronunce R squared) or coefficint of determination
    2. Mean absolute error (MAE)
    3. Mean squared error (MSE)

What R^2 is ?? 

Comares your models prediction with the mean of the target. Value can range from neegative infinity to 1, for rxample, if all your model doest predict the mean of the target, it's R^2 value would be 0. And if your model perfectly predicts a range of numbers, it's R^square would be 1.


In [14]:
from sklearn.metrics import r2_score

## first we have to create an array filled with y_test mean value and the size of the array should be same as y_test
y_test_mean = np.full(len(y_test), y_test.mean())

In [15]:
y_test_mean

array([2.0550031, 2.0550031, 2.0550031, ..., 2.0550031, 2.0550031,
       2.0550031])

In [16]:
len(y_test_mean), len(y_test)

(4128, 4128)

In [17]:
r2_score(y_test, y_test_mean)

0.0

because we input y_test_mean values as predict values 

In [18]:
r2_score(y_test, y_test)

1.0

if predict the same as true value R^2 is 1

In [19]:
y_pred = model.predict(x_test)

In [20]:
r2_score(y_test, y_pred)

0.8065734772187598

### Mean absolute error (MAE)

In [21]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
mae

0.32659871732073664

In [22]:
df = pd.DataFrame({"Actual Value": y_test,
                  "Predicted Value": y_pred})
df["Difference"] = (df["Predicted Value"] - df["Actual Value"])
df["Absolute Difference"] = abs(df["Predicted Value"] - df["Actual Value"])

df

Actual Value  Predicted Value  Difference  Absolute Difference
20046       0.47700         0.493840    0.016840             0.016840
3024        0.45800         0.754940    0.296940             0.296940
15663       5.00001         4.928596   -0.071414             0.071414
20484       2.18600         2.543160    0.357160             0.357160
9814        2.78000         2.331760   -0.448240             0.448240
...             ...              ...         ...                  ...
15362       2.63300         2.220380   -0.412620             0.412620
16623       2.66800         1.947760   -0.720240             0.720240
18086       5.00001         4.836378   -0.163632             0.163632
2144        0.72300         0.717820   -0.005180             0.005180
3665        1.51500         1.679010    0.164010             0.164010

[4128 rows x 4 columns]

MAE : is the average of the absolute differences between predicted values and true values. it gives you an  idea of how wrong your models predictions are

In [23]:
df["Absolute Difference"].mean()

0.32659871732073664

see it is same as mea

### Mean Squared Erro -- MSE

In [24]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
mse

0.2534678520824551

In [25]:
squared = np.square(df["Difference"])
squared.mean()

0.2534678520824551

### evaluation regression models using Scoring parameter

In [26]:
from sklearn.model_selection import cross_val_score
np.random.seed(seed=42)

cv_arr = cross_val_score(model,x,y, cv=5)
cv_arr

array([0.51682388, 0.70279716, 0.74197717, 0.61638204, 0.68243183])

this took nearly 100 seconds since the data size is higher

In [27]:
len(x)

20640

In [28]:
model.score(x_test, y_test)

0.8065734772187598

In [29]:
cv_arr.mean()

0.6520824166120266

In [30]:
print(f"The cross-validation accuracy is : {cv_arr.mean()*100:.2f}%")

The cross-validation accuracy is : 65.21%


Since it take more time to give tha outputs witha huge data i reduce it to 5 000

Try again again by chnging scoring ="" with {accuracy, precision, recall, f1}

    ## this is for the classification models

In [31]:
cv_acc1 = cross_val_score(model, x, y,cv=5, scoring="r2")

In [32]:
cv_acc1

array([0.52250197, 0.70039599, 0.74071892, 0.61721416, 0.6779728 ])

In [33]:
print(f"The cross validation R^2 score is {cv_acc1.mean()*100:.2f}%")

The cross validation R^2 score is 65.18%


#### for Regression models we can change scoring ="" with None, r2, 

simply r2 , neg_mean_absolute_error are some scoring methods only

we just find their value using cross validation method with different different portion of same data set

In [34]:
#mean absolute error : 
cv_mae = cross_val_score(model, x, y, cv=5, scoring="neg_mean_absolute_error")
cv_mae

array([-0.54535682, -0.405814  , -0.43474105, -0.46311862, -0.47328158])

In [35]:
cv_mae.mean()

-0.46446241455910864

In [36]:
#mse | mean squared error
cv_mse = cross_val_score(model, x, y, cv=5, scoring="neg_mean_squared_error")
cv_mse

array([-0.53035867, -0.34754693, -0.37418077, -0.43893707, -0.46479919])

In [37]:
cv_mse.mean()

-0.43116452683014017

## using different eveluation matrics as Scikit-learn Function

Classfication eveluation function

In [38]:
data_frame_cl = pd.read_csv("data/heart-disease.csv")
data_frame_cl

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [39]:
data_frame_cl.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [40]:
data_frame_cl.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [41]:
np.random.seed(42)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

x = data_frame_cl.drop('target', axis = 1)
y = data_frame_cl["target"]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

model = RandomForestClassifier()
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8524590163934426

In [42]:
y_pred = model.predict(x_test)

#Evaluate classifier 
print("Classifier metrics on the test set")
print(f"Accuracy : {accuracy_score(y_test, y_pred)*100:.2f}%")
print(f"Precision score : {precision_score(y_test, y_pred)}")
print(f"Recall score : {recall_score(y_test, y_pred)}")
print(f"f1 : {f1_score(y_test, y_pred)}")

Classifier metrics on the test set
Accuracy : 85.25%
Precision score : 0.8484848484848485
Recall score : 0.875
f1 : 0.8615384615384616


##### Regression eveluation functions

In [43]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

x = housing_df.drop("Target", axis =1)
y = housing_df["Target"]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

model = RandomForestRegressor()
model.fit(x_train, y_train)

##make predictions
y_pred = model.predict(x_test)

#evaluate the regression model
print("Regression model metrics on the test set")
print(f"R^2 Score : {r2_score(y_test, y_pred)*100:.2f}%")
print(f"MAE : {mean_absolute_error(y_test, y_pred)}")
print(f"MSE : {mean_squared_error(y_test, y_pred)}")


Regression model metrics on the test set
R^2 Score : 80.66%
MAE : 0.32659871732073664
MSE : 0.2534678520824551


### 6. Savinf and loading trained machine learning models 

TThere are 2 ways 
1. pickel module
2. joblib module

*pickel*

In [44]:
import pickle

In [46]:
pickle.dump(model, open("models/scikit3_trained_model_regression.pkl", "wb"))

In [48]:
loaded_model = pickle.load(open("models/scikit3_trained_model_regression.pkl", "rb"))

In [51]:
np.random.seed(42)
y_loaded_pred = loaded_model.predict(x_test)
### Evaluating model 
print("Regression model metrics on the test set")
print(f"R^2 Score : {r2_score(y_test, y_loaded_pred)*100:.2f}%")
print(f"MAE : {mean_absolute_error(y_test,y_loaded_pred):.5f}")
print(f"MSE : {mean_squared_error(y_test,y_loaded_pred):.5f}")


Regression model metrics on the test set
R^2 Score : 80.66%
MAE : 0.32660
MSE : 0.25347


**Joblib module**

In [52]:
from joblib import dump, load

dump(model, filename="models/model_scikit3_model.joblib")

['models/model_scikit3_model.joblib']

In [53]:
loaded_joblib_model = load(filename="models/model_scikit3_model.joblib")

#### now we have imported the saved model using joblib

In [54]:
np.random.seed(42)
y_loaded_pred = loaded_joblib_model.predict(x_test)
### Evaluating model 
print("Regression model metrics on the test set")
print(f"R^2 Score : {r2_score(y_test, y_loaded_pred)*100:.2f}%")
print(f"MAE : {mean_absolute_error(y_test,y_loaded_pred):.5f}")
print(f"MSE : {mean_squared_error(y_test,y_loaded_pred):.5f}")

Regression model metrics on the test set
R^2 Score : 80.66%
MAE : 0.32660
MSE : 0.25347
