# Introduction to Scikit-Lear (SK lear)

Workflow:

    *1) Getting data ready
    *2) Choose the right estimator/Algorithrm
    *3) fit the model/algorythem 
    *4) evauating the model
    *5) improve the model
    *6) Save and load a trained model

In [1]:
import numpy as np

In [3]:
import pandas as pd
heart_diease = pd.read_csv("data\heart-disease.csv")
heart_diease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [5]:
# Create X (Features matrix without target, which is the result/lable)
x = heart_diease.drop("target", axis=1)

# create y (lable)
y = heart_diease["target"]

In [11]:
# choose the right model and hyperparameters 
from sklearn.ensemble import RandomForestClassifier 
clf = RandomForestClassifier()

# keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [13]:
# fir the model to the data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [15]:
clf.fit(x_train, y_train);

In [17]:
y_train

118    1
87     1
154    1
284    0
123    1
      ..
267    0
241    0
170    0
206    0
296    0
Name: target, Length: 242, dtype: int64

In [19]:
y_pra = clf.predict(x_test)
y_pra

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [21]:
## here model has predict the result for test data set

In [23]:
clf.score(x_train, y_train)

1.0

In [25]:
clf.score(x_test, y_test)

0.819672131147541

In [27]:
## there are sevaral other methods to check the models accuracy. 

In [29]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print(classification_report(y_test, y_pra))

              precision    recall  f1-score   support

           0       0.81      0.78      0.79        27
           1       0.83      0.85      0.84        34

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [31]:
print(accuracy_score(y_test, y_pra))

0.819672131147541


In [33]:
print(confusion_matrix(y_test, y_pra))

[[21  6]
 [ 5 29]]


In [35]:
np.random.seed(seed= 42)

for i in range(1,100,2):
    clf.n_estimators=i;
    print(f"Trying model with {i} Estimator !!")
    clf.fit(x_train, y_train)
    print(f"Accuracy : {clf.score(x_test, y_test)*100:.2f} % \n")

## :.2f by adding this we can make it round to the 2 decimal places

Trying model with 1 Estimator !!
Accuracy : 75.41 % 

Trying model with 3 Estimator !!
Accuracy : 72.13 % 

Trying model with 5 Estimator !!
Accuracy : 68.85 % 

Trying model with 7 Estimator !!
Accuracy : 75.41 % 

Trying model with 9 Estimator !!
Accuracy : 80.33 % 

Trying model with 11 Estimator !!
Accuracy : 70.49 % 

Trying model with 13 Estimator !!
Accuracy : 85.25 % 

Trying model with 15 Estimator !!
Accuracy : 81.97 % 

Trying model with 17 Estimator !!
Accuracy : 81.97 % 

Trying model with 19 Estimator !!
Accuracy : 83.61 % 

Trying model with 21 Estimator !!
Accuracy : 78.69 % 

Trying model with 23 Estimator !!
Accuracy : 78.69 % 

Trying model with 25 Estimator !!
Accuracy : 78.69 % 

Trying model with 27 Estimator !!
Accuracy : 80.33 % 

Trying model with 29 Estimator !!
Accuracy : 77.05 % 

Trying model with 31 Estimator !!
Accuracy : 77.05 % 

Trying model with 33 Estimator !!
Accuracy : 75.41 % 

Trying model with 35 Estimator !!
Accuracy : 83.61 % 

Trying model wi

In [37]:
## Accuracy is higher when Estimator is 1

In [39]:
# Save the model and load it

In [41]:
import pickle
pickle.dump(clf, open("models\heart_dieasea_detector_model_1_using_RF.pkl", "wb"))

In [43]:
loaded_model = pickle.load(open("models\heart_dieasea_detector_model_1_using_RF.pkl", "rb"))

In [45]:
loaded_model

RandomForestClassifier(n_estimators=99)

In [47]:
loaded_model.score(x_test, y_test)

0.7868852459016393

this score has given when estimator == 99

#### Important things:

get ready the data to be used with machine learning

3 main things we have to do:
    
    1. split data into features and labels (usually x and y)
    2.filling(also called imputing) or disregarding missing values 
    3. convert non-numerical values into numerical values | also calling feature encoding

## Make data redy to machine learning 

### 1.1 Make data all numerical 

In [54]:
car_sale = pd.read_csv("data\car-sales-extended.csv")

In [56]:
car_sale


Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [58]:
car_sale.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [60]:
car_sale.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [62]:
x = car_sale.drop("Price", axis=1)
y = car_sale["Price"]

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [66]:
## lets build the machine learning model, we have to select the machine learning model that suit for our project
## to get undestand about all the models read the sk learn documentation 

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test, y_test)

ValueError: could not convert string to float: 'Honda'

models can deal with nun numeric data, so we have to convert non numerical data into numerical data

In [69]:
## Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

transformed_X = transformer.fit_transform(x)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [71]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [73]:
dummies = pd.get_dummies(car_sale[["Colour", "Make", "Doors"]])
dummies

Doors  Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  \
0        4         False        False         False       False          True   
1        5         False         True         False       False         False   
2        4         False        False         False       False          True   
3        4         False        False         False       False          True   
4        3         False         True         False       False         False   
..     ...           ...          ...           ...         ...           ...   
995      4          True        False         False       False         False   
996      3         False        False         False       False          True   
997      4         False         True         False       False         False   
998      4         False        False         False       False          True   
999      4         False         True         False       False         False   

     Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  
0       False        True        False        False  
1        True       False        False        False  
2       False        True        False        False  
3       False       False        False         True  
4       False       False         True        False  
..        ...         ...          ...          ...  
995     False       False        False         True  
996     False       False         True        False  
997     False       False         True        False  
998     False        True        False        False  
999     False       False        False         True  

[1000 rows x 10 columns]

In [75]:
np.random.seed(seed = 42)
## If this is not the score change from time to time, but?
## because, split function mixed the data before split in to test and train test at every time it is run


x = pd.DataFrame(transformed_X)
x

x_train, x_test, y_train, y_test = train_test_split(x,y)
model.fit(x_train, y_train)
model.score(x_test, y_test) 

0.26971662820358044

### 1.2 what if having missing values

    1. fill them with some value || Imputation
    2. Remove the sample with missing data altogether

In [78]:
car_sale_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")

In [80]:
car_sale_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [82]:
x = car_sale_missing.drop("Price", axis = 1)
y = car_sale_missing["Price"]


In [84]:
## gives the number of missing data
car_sale_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [86]:
x

Make Colour  Odometer (KM)  Doors
0     Honda  White        35431.0    4.0
1       BMW   Blue       192714.0    5.0
2     Honda  White        84714.0    4.0
3    Toyota  White       154365.0    4.0
4    Nissan   Blue       181577.0    3.0
..      ...    ...            ...    ...
995  Toyota  Black        35820.0    4.0
996     NaN  White       155144.0    3.0
997  Nissan   Blue        66604.0    4.0
998   Honda  White       215883.0    4.0
999  Toyota   Blue       248360.0    4.0

[1000 rows x 4 columns]

In [88]:
x_train, x_test, y_train, y_test  = train_test_split(x, y)

In [90]:
car_sale_missing.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [92]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot = OneHotEncoder()
catagorical_features = ["Make", "Colour", "Doors"]
Transformer = ColumnTransformer([("one_hot",one_hot, catagorical_features)], remainder="passthrough")
transformed_x = transformer.fit_transform(x_train)
transformed_x

<750x16 sparse matrix of type '<class 'numpy.float64'>'
	with 3000 stored elements in Compressed Sparse Row format>

In [94]:
car_sale_missing.head(10)

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [96]:
##lets fill the missing values in "Make colums"
car_sale_missing["Make"].fillna("missing", inplace=True)

##lets fill the colour columns
car_sale_missing["Colour"].fillna("missing", inplace=True)

##lets fill the odometer columns
car_sale_missing["Odometer (KM)"].fillna(car_sale_missing["Odometer (KM)"].mean(), inplace=True)

## to check the avarage number of the doors, it is very closer to the 4
##car_sale_missing["Doors"].mean()

##lets fill the Doors column
car_sale_missing["Doors"].fillna(4, inplace=True)

car_sale_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

when the pradicting colums havins Nan we can not fill  them and we do not usually. instead of fill them we just delete those rows 

In [99]:
car_sale_missing.dropna(inplace = True)

In [101]:
car_sale_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [103]:
len(car_sale_missing)

950

In [105]:
x = car_sale_missing.drop("Price", axis = 1)
y = car_sale_missing["Price"]
len(x)

950

In [107]:
## Turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)],
                                remainder="passthrough",
                               sparse_threshold=0)

transformed_X = transformer.fit_transform(x)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [109]:
np.random.seed(seed = 42)
x_train, x_test, y_train, y_test = train_test_split(transformed_X, y )

In [111]:
model.fit(x_train, y_train)

RandomForestRegressor()

In [113]:
model.score(x_test, y_test)

0.21064150925394065

### Filling missing values with SK learns

In [134]:
car_sale_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sale_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [136]:
car_sale_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [138]:
car_sale_missing.dropna(subset=["Price"], inplace = True)
car_sale_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [151]:
## split in to x and y
x = car_sale_missing.drop("Price", axis = 1)
y = car_sale_missing["Price"]

In [153]:
x.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [169]:
##filll NaN values with sk learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
num_imputer = SimpleImputer(strategy="mean")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)

cat_columns = ["Make", "Colour"]
num_columns = ["Odometer (KM)"]
door_columns = ["Doors"]

imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_columns),
    ("door_imputer", door_imputer, door_columns),
    ("num_imputer", num_imputer, num_columns)
], remainder="passthrough")

filled_x = imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [173]:
filled_car_sale = pd.DataFrame(filled_x, columns=["Make", "Colour", "Door", "Odometer (Km)"])
filled_car_sale

Make Colour Door Odometer (Km)
0      Honda  White  4.0       35431.0
1        BMW   Blue  5.0      192714.0
2      Honda  White  4.0       84714.0
3     Toyota  White  4.0      154365.0
4     Nissan   Blue  3.0      181577.0
..       ...    ...  ...           ...
945   Toyota  Black  4.0       35820.0
946  missing  White  3.0      155144.0
947   Nissan   Blue  4.0       66604.0
948    Honda  White  4.0      215883.0
949   Toyota   Blue  4.0      248360.0

[950 rows x 4 columns]

In [177]:
filled_car_sale.isna().sum()

Make             0
Colour           0
Door             0
Odometer (Km)    0
dtype: int64

In [183]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot = OneHotEncoder()
catagorical_columns = ["Make", "Door", "Colour"]

transformer = ColumnTransformer([("one_hot", one_hot, catagorical_columns)], remainder="passthrough"
                               ,sparse_threshold=0)

transformed_x = transformer.fit_transform(filled_car_sale)
transformed_x


array([[0.0, 1.0, 0.0, ..., 1.0, 0.0, 35431.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 192714.0],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 84714.0],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 66604.0],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 215883.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 248360.0]], dtype=object)

In [197]:
len(transformed_x)

950

In [199]:
np.random.seed(seed = 42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.22177101581049175

data get more, accuracy get higher